apiVersion: v1
kind: Service
metadata:
  labels:
    app: notes
    component: api
  name: notes
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9001
  selector:
    app: notes
  type: NodePort